name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build and Assemble Release APK
      run: ./gradlew assembleRelease

    - name: Save APK to a temporary directory
      if: success()
      run: mkdir -p outputs && cp app/build/outputs/apk/release/app-release.apk outputs/

    - name: Upload APK as artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: outputs/app-release.apk
